### ISSUE TITLE
Replace ALLOW_ALL with Read+Modify+Write / use default group options instead 

### ISSUE THREAD

**Issue by itaysaadia** [MeitarR/NotABot#1]
In the current code, the default / modified group options are override with ALLOW_ALL option.
consider to replace it to something like:
```python
default_options = telegram_api.get_group_permissions(new_user)
telegram_api.restrict_user(new_user, DENY_ALL)
# wait for human verification...
if user.is_human:
    telegram_api.restrict_user(new_user, default_option)
else:
    kick()
```

**Comment by MeitarR** [comment]
No one can give permission that disabled on the chat level.
Its will fail silently 

So all true means in restrict user.

For example I disabled the `send media` for the group
This is a permissions for specific member:
![example image](https://user-images.githubusercontent.com/14138694/102707595-18eaa500-42a5-11eb-8b2f-5d2b391a4aeb.jpg)
