### ISSUE TITLE
@admins command

### ISSUE THREAD

**Issue by jonatan1609** [MeitarR/NotABot#4]
It would be nice if the bot could reply the admins list by @admins command

**Comment by MeitarR** [comment]
To make sure I understand correctly, you mean:
a user writes a message that contains the word "@admins" and then the bot reply to that message with mention of all the admins?

**Comment by jonatan1609** [comment]
**yes, i do**
I guess it would be better if the command would be ^[/@]admins$.
Since people sometimes write "@admins" in their message and they don't mean to mention all admins, for example, in order to explain how to mention admins, etc.

**Comment by jonatan1609** [comment]
have you been working on that? :D￼
